export const HOME_ACTION_TYPES = {
  SET_POSTS: 'home/SET_POSTS',
  SET_IS_CREATE_POST_OPEN: 'home/SET_IS_CREATE_POST_OPEN',
  SET_POST_CONTENT: 'home/SET_POST_CONTENT',
  SET_SELECTED_IMAGES: 'home/SET_SELECTED_IMAGES',
  SET_SELECTED_VIDEOS: 'home/SET_SELECTED_VIDEOS',
  SET_POST_TYPE: 'home/SET_POST_TYPE',
  SET_IS_PUBLIC: 'home/SET_IS_PUBLIC',
  ADD_POST: 'home/ADD_POST',
  UPDATE_POST: 'home/UPDATE_POST',
  DELETE_POST: 'home/DELETE_POST',
  LIKE_POST: 'home/LIKE_POST',
  UNLIKE_POST: 'home/UNLIKE_POST',
  RESET_POST_FORM: 'home/RESET_POST_FORM'
}
