export const HOME_ACTION_TYPES = {
  SET_POSTS: 'home/SET_POSTS',
  SET_IS_CREATE_POST_OPEN: 'home/SET_IS_CREATE_POST_OPEN',
  SET_POST_CONTENT: 'home/SET_POST_CONTENT',
  SET_SELECTED_IMAGES: 'home/SET_SELECTED_IMAGES',
  SET_SELECTED_VIDEOS: 'home/SET_SELECTED_VIDEOS',
  SET_POST_TYPE: 'home/SET_POST_TYPE',
  SET_IS_PUBLIC: 'home/SET_IS_PUBLIC',
  ADD_POST: 'home/ADD_POST',
  UPDATE_POST: 'home/UPDATE_POST',
  DELETE_POST: 'home/DELETE_POST',
  LIKE_POST: 'home/LIKE_POST',
  UNLIKE_POST: 'home/UNLIKE_POST',
  DISLIKE_POST: 'home/DISLIKE_POST',
  UNDISLIKE_POST: 'home/UNDISLIKE_POST',
  RESET_POST_FORM: 'home/RESET_POST_FORM',
  
  // Async action types for thunk operations
  // Update Post
  UPDATE_POST_REQUEST: 'home/UPDATE_POST_REQUEST',
  UPDATE_POST_SUCCESS: 'home/UPDATE_POST_SUCCESS',
  UPDATE_POST_ERROR: 'home/UPDATE_POST_ERROR',
  
  // Delete Post
  DELETE_POST_REQUEST: 'home/DELETE_POST_REQUEST',
  DELETE_POST_SUCCESS: 'home/DELETE_POST_SUCCESS',
  DELETE_POST_ERROR: 'home/DELETE_POST_ERROR',
  
  // Fetch Posts
  FETCH_POSTS_REQUEST: 'home/FETCH_POSTS_REQUEST',
  FETCH_POSTS_SUCCESS: 'home/FETCH_POSTS_SUCCESS',
  FETCH_POSTS_ERROR: 'home/FETCH_POSTS_ERROR',
  
  // Create Post
  CREATE_POST_REQUEST: 'home/CREATE_POST_REQUEST',
  CREATE_POST_SUCCESS: 'home/CREATE_POST_SUCCESS',
  CREATE_POST_ERROR: 'home/CREATE_POST_ERROR',
  
  // Like Post
  LIKE_POST_REQUEST: 'home/LIKE_POST_REQUEST',
  LIKE_POST_SUCCESS: 'home/LIKE_POST_SUCCESS',
  LIKE_POST_ERROR: 'home/LIKE_POST_ERROR',
  
  // Unlike Post
  UNLIKE_POST_REQUEST: 'home/UNLIKE_POST_REQUEST',
  UNLIKE_POST_SUCCESS: 'home/UNLIKE_POST_SUCCESS',
  UNLIKE_POST_ERROR: 'home/UNLIKE_POST_ERROR',
  
  // Dislike Post
  DISLIKE_POST_REQUEST: 'home/DISLIKE_POST_REQUEST',
  DISLIKE_POST_SUCCESS: 'home/DISLIKE_POST_SUCCESS',
  DISLIKE_POST_ERROR: 'home/DISLIKE_POST_ERROR',
  
  // Undislike Post
  UNDISLIKE_POST_REQUEST: 'home/UNDISLIKE_POST_REQUEST',
  UNDISLIKE_POST_SUCCESS: 'home/UNDISLIKE_POST_SUCCESS',
  UNDISLIKE_POST_ERROR: 'home/UNDISLIKE_POST_ERROR'
}
