export const LEADERBOARDS_ACTION_TYPES = {
  SET_USER_STATS: 'leaderboards/SET_USER_STATS',
  SET_RANKINGS: 'leaderboards/SET_RANKINGS',
  SET_SELECTED_TAB: 'leaderboards/SET_SELECTED_TAB',
  SET_OVERALL_RANKINGS: 'leaderboards/SET_OVERALL_RANKINGS',
  SET_WEEKLY_RANKINGS: 'leaderboards/SET_WEEKLY_RANKINGS',
  SET_STREAKS_RANKINGS: 'leaderboards/SET_STREAKS_RANKINGS',
  SET_IS_LOADING: 'leaderboards/SET_IS_LOADING',
  SET_ERROR: 'leaderboards/SET_ERROR',
  UPDATE_USER_RANK: 'leaderboards/UPDATE_USER_RANK',
  UPDATE_USER_POINTS: 'leaderboards/UPDATE_USER_POINTS',
  REFRESH_RANKINGS: 'leaderboards/REFRESH_RANKINGS'
}
