export const TRACKING_ACTION_TYPES = {
  SET_TRACKING_DATA: 'tracking/SET_TRACKING_DATA',
  SET_WEEKLY_PROGRESS: 'tracking/SET_WEEKLY_PROGRESS',
  SET_TASK_COMPLETION_DATA: 'tracking/SET_TASK_COMPLETION_DATA',
  SET_DAILY_POINTS_DATA: 'tracking/SET_DAILY_POINTS_DATA',
  SET_CURRENT_SLIDE: 'tracking/SET_CURRENT_SLIDE',
  SET_TIME_PERIOD: 'tracking/SET_TIME_PERIOD',
  SET_SHOW_CUSTOM_DATE_PICKER: 'tracking/SET_SHOW_CUSTOM_DATE_PICKER',
  SET_CUSTOM_DATE_FROM: 'tracking/SET_CUSTOM_DATE_FROM',
  SET_CUSTOM_DATE_TO: 'tracking/SET_CUSTOM_DATE_TO',
  ADD_TRACKING_ENTRY: 'tracking/ADD_TRACKING_ENTRY',
  UPDATE_TRACKING_ENTRY: 'tracking/UPDATE_TRACKING_ENTRY',
  DELETE_TRACKING_ENTRY: 'tracking/DELETE_TRACKING_ENTRY',
  NEXT_SLIDE: 'tracking/NEXT_SLIDE',
  PREV_SLIDE: 'tracking/PREV_SLIDE',
  NAVIGATE_TIME_PERIOD: 'tracking/NAVIGATE_TIME_PERIOD',
  APPLY_CUSTOM_DATE_RANGE: 'tracking/APPLY_CUSTOM_DATE_RANGE'
}
