export const TRACKING_ACTION_TYPES = {
  // UI State Actions
  SET_CURRENT_SLIDE: 'tracking/SET_CURRENT_SLIDE',
  SET_TIME_PERIOD: 'tracking/SET_TIME_PERIOD',
  SET_SHOW_CUSTOM_DATE_PICKER: 'tracking/SET_SHOW_CUSTOM_DATE_PICKER',
  SET_CUSTOM_DATE_FROM: 'tracking/SET_CUSTOM_DATE_FROM',
  SET_CUSTOM_DATE_TO: 'tracking/SET_CUSTOM_DATE_TO',
  
  // Chart Navigation Actions
  NEXT_SLIDE: 'tracking/NEXT_SLIDE',
  PREV_SLIDE: 'tracking/PREV_SLIDE',
  NAVIGATE_TIME_PERIOD: 'tracking/NAVIGATE_TIME_PERIOD',
  APPLY_CUSTOM_DATE_RANGE: 'tracking/APPLY_CUSTOM_DATE_RANGE',
  
  // Firebase Data Actions
  SET_TRACKING_SESSIONS: 'tracking/SET_TRACKING_SESSIONS',
  SET_WEEKLY_PROGRESS_DATA: 'tracking/SET_WEEKLY_PROGRESS_DATA',
  SET_TASK_COMPLETION_DATA: 'tracking/SET_TASK_COMPLETION_DATA',
  SET_DAILY_POINTS_DATA: 'tracking/SET_DAILY_POINTS_DATA',
  SET_CATEGORIES_DATA: 'tracking/SET_CATEGORIES_DATA',
  
  // Async action types for time tracking sessions
  CREATE_SESSION_REQUEST: 'tracking/CREATE_SESSION_REQUEST',
  CREATE_SESSION_SUCCESS: 'tracking/CREATE_SESSION_SUCCESS',
  CREATE_SESSION_ERROR: 'tracking/CREATE_SESSION_ERROR',
  
  
}
