export const POMODORO_ACTION_TYPES = {
  // Session State Actions
  SET_ACTIVE_SESSION: 'pomodoro/SET_ACTIVE_SESSION',
  SET_SESSION_STATUS: 'pomodoro/SET_SESSION_STATUS',
  SET_TIME_REMAINING: 'pomodoro/SET_TIME_REMAINING',
  SET_ELAPSED_TIME: 'pomodoro/SET_ELAPSED_TIME',
  SET_IS_RUNNING: 'pomodoro/SET_IS_RUNNING',
  SET_SESSION_DURATION: 'pomodoro/SET_SESSION_DURATION',
  
  // Configuration Actions
  SET_DEFAULT_DURATION: 'pomodoro/SET_DEFAULT_DURATION',
  SET_SELECTED_TASK: 'pomodoro/SET_SELECTED_TASK',
  SET_AUTO_START_BREAK: 'pomodoro/SET_AUTO_START_BREAK',
  SET_AUTO_START_POMODORO: 'pomodoro/SET_AUTO_START_POMODORO',
  
  // Session History Actions
  SET_USER_SESSIONS: 'pomodoro/SET_USER_SESSIONS',
  SET_TASK_SESSIONS: 'pomodoro/SET_TASK_SESSIONS',
  SET_SESSION_STATS: 'pomodoro/SET_SESSION_STATS',
  
  // Timer Actions
  START_TIMER: 'pomodoro/START_TIMER',
  PAUSE_TIMER: 'pomodoro/PAUSE_TIMER',
  RESUME_TIMER: 'pomodoro/RESUME_TIMER',
  STOP_TIMER: 'pomodoro/STOP_TIMER',
  RESET_TIMER: 'pomodoro/RESET_TIMER',
  TICK_TIMER: 'pomodoro/TICK_TIMER',
  
  // Async action types for focus sessions
  START_SESSION_REQUEST: 'pomodoro/START_SESSION_REQUEST',
  START_SESSION_SUCCESS: 'pomodoro/START_SESSION_SUCCESS',
  START_SESSION_ERROR: 'pomodoro/START_SESSION_ERROR',
  
  COMPLETE_SESSION_REQUEST: 'pomodoro/COMPLETE_SESSION_REQUEST',
  COMPLETE_SESSION_SUCCESS: 'pomodoro/COMPLETE_SESSION_SUCCESS',
  COMPLETE_SESSION_ERROR: 'pomodoro/COMPLETE_SESSION_ERROR',
  
  DELETE_SESSION_REQUEST: 'pomodoro/DELETE_SESSION_REQUEST',
  DELETE_SESSION_SUCCESS: 'pomodoro/DELETE_SESSION_SUCCESS',
  DELETE_SESSION_ERROR: 'pomodoro/DELETE_SESSION_ERROR',
  
  LOAD_USER_SESSIONS_REQUEST: 'pomodoro/LOAD_USER_SESSIONS_REQUEST',
  LOAD_USER_SESSIONS_SUCCESS: 'pomodoro/LOAD_USER_SESSIONS_SUCCESS',
  LOAD_USER_SESSIONS_ERROR: 'pomodoro/LOAD_USER_SESSIONS_ERROR',
  
  LOAD_TASK_SESSIONS_REQUEST: 'pomodoro/LOAD_TASK_SESSIONS_REQUEST',
  LOAD_TASK_SESSIONS_SUCCESS: 'pomodoro/LOAD_TASK_SESSIONS_SUCCESS',
  LOAD_TASK_SESSIONS_ERROR: 'pomodoro/LOAD_TASK_SESSIONS_ERROR',
  
  LOAD_SESSION_STATS_REQUEST: 'pomodoro/LOAD_SESSION_STATS_REQUEST',
  LOAD_SESSION_STATS_SUCCESS: 'pomodoro/LOAD_SESSION_STATS_SUCCESS',
  LOAD_SESSION_STATS_ERROR: 'pomodoro/LOAD_SESSION_STATS_ERROR',
  
  // UI Actions
  SET_SHOW_TIMER_MODAL: 'pomodoro/SET_SHOW_TIMER_MODAL',
  SET_SHOW_HISTORY_MODAL: 'pomodoro/SET_SHOW_HISTORY_MODAL',
  SET_SHOW_STATS_MODAL: 'pomodoro/SET_SHOW_STATS_MODAL',
  
  // Loading and Error States
  SET_LOADING: 'pomodoro/SET_LOADING',
  SET_ERROR: 'pomodoro/SET_ERROR',
  CLEAR_ERROR: 'pomodoro/CLEAR_ERROR',
}

