export const AUTH_ACTION_TYPES = {
  // Core user state
  SET_CURRENT_USER: 'auth/SET_CURRENT_USER',
  SET_LOADING: 'auth/SET_LOADING',
  SET_ERROR: 'auth/SET_ERROR',
  CLEAR_ERROR: 'auth/CLEAR_ERROR',
  
  // Form data management
  UPDATE_SIGN_UP_FORM: 'auth/UPDATE_SIGN_UP_FORM',
  UPDATE_SIGN_IN_FORM: 'auth/UPDATE_SIGN_IN_FORM',
  CLEAR_FORM_DATA: 'auth/CLEAR_FORM_DATA',
  
  // Only for operations that need loading states
  SIGN_IN_START: 'auth/SIGN_IN_START',
  SIGN_IN_SUCCESS: 'auth/SIGN_IN_SUCCESS',
  SIGN_IN_FAILED: 'auth/SIGN_IN_FAILED',
  
  SIGN_UP_START: 'auth/SIGN_UP_START',
  SIGN_UP_SUCCESS: 'auth/SIGN_UP_SUCCESS',
  SIGN_UP_FAILED: 'auth/SIGN_UP_FAILED',
  
  // Google Auth (async operation)
  GOOGLE_SIGN_IN_START: 'auth/GOOGLE_SIGN_IN_START',
  GOOGLE_SIGN_IN_SUCCESS: 'auth/GOOGLE_SIGN_IN_SUCCESS',
  GOOGLE_SIGN_IN_FAILED: 'auth/GOOGLE_SIGN_IN_FAILED',
  
  // Profile updates (async operation)
  UPDATE_USER_PROFILE_START: 'auth/UPDATE_USER_PROFILE_START',
  UPDATE_USER_PROFILE_SUCCESS: 'auth/UPDATE_USER_PROFILE_SUCCESS',
  UPDATE_USER_PROFILE_FAILED: 'auth/UPDATE_USER_PROFILE_FAILED'
}
