export const MORE_ACTION_TYPES = {
  SET_MORE_SECTIONS: 'more/SET_MORE_SECTIONS',
  SET_QUICK_ACTIONS: 'more/SET_QUICK_ACTIONS',
  SET_SEARCH_QUERY: 'more/SET_SEARCH_QUERY',
  SET_FILTERED_SECTIONS: 'more/SET_FILTERED_SECTIONS',
  SET_SHOW_SEARCH: 'more/SET_SHOW_SEARCH',
  SET_SHOW_NOTIFICATIONS: 'more/SET_SHOW_NOTIFICATIONS',
  HANDLE_QUICK_ACTION: 'more/HANDLE_QUICK_ACTION',
  HANDLE_ITEM_PRESS: 'more/HANDLE_ITEM_PRESS',
  HANDLE_SEARCH_PRESS: 'more/HANDLE_SEARCH_PRESS',
  HANDLE_NOTIFICATION_PRESS: 'more/HANDLE_NOTIFICATION_PRESS',
  FILTER_SECTIONS: 'more/FILTER_SECTIONS',
  CLEAR_SEARCH: 'more/CLEAR_SEARCH'
}
