export const PROFILE_ACTION_TYPES = {
  SET_USER_DATA: 'profile/SET_USER_DATA',
  SET_NOTIFICATIONS_ENABLED: 'profile/SET_NOTIFICATIONS_ENABLED',
  SET_SHOW_SETTINGS: 'profile/SET_SHOW_SETTINGS',
  SET_SHOW_EDIT_PROFILE: 'profile/SET_SHOW_EDIT_PROFILE',
  SET_USER_NAME: 'profile/SET_USER_NAME',
  SET_USER_EMAIL: 'profile/SET_USER_EMAIL',
  SET_USER_AVATAR: 'profile/SET_USER_AVATAR',
  SET_USER_STATS: 'profile/SET_USER_STATS',
  SET_ACHIEVEMENTS: 'profile/SET_ACHIEVEMENTS',
  UPDATE_PROFILE: 'profile/UPDATE_PROFILE',
  SAVE_PROFILE_CHANGES: 'profile/SAVE_PROFILE_CHANGES',
  TOGGLE_NOTIFICATIONS: 'profile/TOGGLE_NOTIFICATIONS',
  OPEN_SETTINGS: 'profile/OPEN_SETTINGS',
  CLOSE_SETTINGS: 'profile/CLOSE_SETTINGS',
  OPEN_EDIT_PROFILE: 'profile/OPEN_EDIT_PROFILE',
  CLOSE_EDIT_PROFILE: 'profile/CLOSE_EDIT_PROFILE',
  
  // Firebase Profile Actions
  FETCH_USER_PROFILE_START: 'profile/FETCH_USER_PROFILE_START',
  FETCH_USER_PROFILE_SUCCESS: 'profile/FETCH_USER_PROFILE_SUCCESS',
  FETCH_USER_PROFILE_FAILED: 'profile/FETCH_USER_PROFILE_FAILED',
  UPDATE_USER_PROFILE_START: 'profile/UPDATE_USER_PROFILE_START',
  UPDATE_USER_PROFILE_SUCCESS: 'profile/UPDATE_USER_PROFILE_SUCCESS',
  UPDATE_USER_PROFILE_FAILED: 'profile/UPDATE_USER_PROFILE_FAILED'
}
